name: Simulate

on:
  push:
  pull_request:

jobs:

  simulate:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: See what's here
      run: ls -al && which python && python --version
    - name: check file  
      run: ls hdl/sim/run.py

    - name: Run VUnit tests
      uses: VUnit/vunit_action@master
      with:
        cmd: hdl/sim/run.py

  manual-installs:
    runs-on: ubuntu-latest
    steps:
      - name: install ghdl
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: mcode
          investigate: true
      - name: install VUnit
        run: pip install --pre vunit_hdl
      - name: Checkout Repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: run tests
        run: |
          cd hdl/sim
          ls -al
          echo $PATH
          ls /home/runner/work/fpca/fpca/install/bin
          /home/runner/work/fpca/fpca/install/bin/ghdl --version
          which ghdl
          python run_ci.py -m



  # container-job:
  #   runs-on: ubuntu-latest
  #   container: ghdl/vunit:mcode-master
  #   steps:

  #   - uses: actions/checkout@v2

  #   - run: python3 hdl/sim/run.py


  # container-step:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - uses: actions/checkout@v2

  #   - uses: docker://ghdl/vunit:mcode-master
  #     with:
  #       args: hdl/sim/run.py
