name: Simulate

on:
  push:
  pull_request:

jobs:

  simulate:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: See what's here
      run: ls -al && which python && python --version
    - name: check file  
      run: ls hdl/sim/run.py

    - name: Run VUnit tests
      uses: VUnit/vunit_action@master
      with:
        cmd: hdl/sim/run.py


  # container-job:
  #   runs-on: ubuntu-latest
  #   container: ghdl/vunit:mcode-master
  #   steps:

  #   - uses: actions/checkout@v2

  #   - run: python3 hdl/sim/run.py


  # container-step:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - uses: actions/checkout@v2

  #   - uses: docker://ghdl/vunit:mcode-master
  #     with:
  #       args: hdl/sim/run.py
